{% set name = "gnome-icon-theme" %}
{% set version = "3.12.0" %}
{% set major_version = version.split('.')[0] %}
{% set minor_version = version.split('.')[1] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.gnome.org/sources/{{ name }}/{{ major_version }}.{{ minor_version }}/{{ name }}-{{ version }}.tar.xz
  sha256: 359e720b9202d3aba8d477752c4cd11eced368182281d51ffd64c8572b4e503a

build:
  number: 0
  # it would be nice if this were noarch: generic because it just installs some files,
  # but we want them in $PREFIX on Unix and %LIBRARY_PREFIX% on Windows
  # noarch: generic

requirements:
  build:
    - make  # [unix]

test:
  commands:
    - test -f $PREFIX/share/icons/gnome-icon-theme/index.theme  # [unix]
    - if not exist %PREFIX%\Library\share\icons\gnome-icon-theme\index.theme exit 1  # [win]

about:
  home: https://developer.gnome.org
  license: LGPL-3.0-or-later OR CC-BY-SA-3.0
  license_family: LGPL
  license_file: COPYING
  summary: 'This package contains the default icon theme used by the GNOME'

extra:
  recipe-maintainers:
    - Tobias-Fischer
