{% set name = "gnome-icon-theme" %}
{% set version = "3.12.0" %}
{% set major_version = version.split('.')[0] %}
{% set minor_version = version.split('.')[1] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.gnome.org/sources/{{ name }}/{{ major_version }}.{{ minor_version }}/{{ name }}-{{ version }}.tar.xz
  sha256: 359e720b9202d3aba8d477752c4cd11eced368182281d51ffd64c8572b4e503a
  patches:
    - 0001-configure.ac-Do-not-manually-set-localedir.patch

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - pkg-config
    - automake
    - autoconf
    - gnuconfig
    - gettext     # [build_platform != target_platform]
    - libtool
  host:
    - intltool
    - icon-naming-utils
    - gtk3
    - gettext

test:
  commands:
    - test -f $PREFIX/share/pkgconfig/gnome-icon-theme.pc  # [unix]
    - test -f $PREFIX/share/icons/gnome/index.theme  # [unix]

about:
  home: https://developer.gnome.org
  license: LGPL-3.0-or-later OR CC-BY-SA-3.0
  license_family: LGPL
  license_file: COPYING
  summary: 'This package contains the default icon theme used by the GNOME'

extra:
  recipe-maintainers:
    - Tobias-Fischer
