{% set name = "icon-naming-utils" %}
{% set version = "0.8.90" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://deb.debian.org/debian/pool/main/i/{{ name }}/{{ name }}_{{ version }}.orig.tar.gz
  sha256: 044ab2199ed8c6a55ce36fd4fcd8b8021a5e21f5bab028c0a7cdcf52a5902e1c

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make  # [unix]
  host:
    - perl-xml-simple

test:
  commands:
    - test -f $PREFIX/libexec/icon-name-mapping  # [unix]
    - test -f $PREFIX/share/icon-naming-utils/legacy-icon-mapping.xml  # [unix]
    - test -f $PREFIX/share/pkgconfig/icon-naming-utils.pc  # [unix]

about:
  home: https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: 'Script to handle icon names in desktop icon themes'

extra:
  recipe-maintainers:
    - Tobias-Fischer
