{% set name = "pyrr" %}
{% set version = "0.10.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyrr-{{ version }}.tar.gz
  sha256: 3c0f7b20326e71f706a610d58f2190fff73af01eef60c19cb188b186f0ec7e1d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - multipledispatch

test:
  imports:
    - pyrr
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/adamlwgriffiths/Pyrr
  summary: 3D mathematical functions using NumPy
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
