{% set name = "terality" %}
{% set version = "0.14.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/terality-{{ version }}.tar.gz
  sha256: aff41607bbabdc2b32c33a09d6e4d9f0fdc036bb90b8cfa597d5081c98b3a600

build:
  entry_points:
    - terality = terality._terality.bin.__main__:cli
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
    - poetry
  run:
    - boto3
    - click
    - importlib_metadata
    - numpy
    - pandas
    - protobuf
    - pyarrow >=6.0.0,<7.0.0
    - pydantic
    - python >=3.6
    - requests
    - sentry-sdk
    - tqdm

test:
  imports:
    - common_client_scheduler
    - terality
    - terality_serde
  commands:
    - pip check
    - terality --help
  requires:
    - pip

about:
  home: https://terality.com/
  summary: The Data Processing Engine for Data Scientists
  license: PROPRIETARY
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Tobias-Fischer
