{% set name = "perl-xml-simple" %}
{% set version = "2.25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/G/GR/GRANTM/XML-Simple-{{ version }}.tar.gz
  sha256: 531fddaebea2416743eb5c4fdfab028f502123d9a220405a4100e68fc480dbf8

build:
  noarch: generic
  number: 3

requirements:
  build:
    - make
  host:
    - perl
    - perl-xml-namespacesupport
    - perl-xml-sax-expat
    - perl-xml-sax

  run:
    - perl
    - perl-xml-sax-expat
    - perl-xml-sax
    - perl-xml-namespacesupport

test:
  # Perl 'use' tests
  imports:
    - XML::Simple

about:
  home: http://metacpan.org/pod/XML-Simple
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  summary: 'An API for simple XML files'

extra:
  recipe-maintainers:
    - Tobias-Fischer
