{% set name = "liburcu" %}
{% set version = "0.13.2" %}

package:
  name: liburcu
  version: '{{ version }}'

source:
  url: https://lttng.org/files/urcu/userspace-rcu-{{ version }}.tar.bz2
  sha256: 1213fd9f1b0b74da7de2bb74335b76098db9738fec5d3cdc07c0c524f34fc032

build:
  number: 0
  skip: True  # [not linux]
  run_exports:
    - '{{ pin_subpackage(name, max_pin="x.x.x") }}'

requirements:
  build:
    - '{{ compiler("c") }}'
    - '{{ compiler("cxx") }}'
    - automake
    - libtool
    - gnuconfig
    - make

test:
  commands:
    - test -f ${PREFIX}/lib/liburcu${SHLIB_EXT}


about:
  home: http://liburcu.org
  summary: liburcu-cds provides efficient data structures based on RCU and lock-free algorithms.
  license: LGPL-2.1-only
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - TobiasFischer
